# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Wave Energy: An Ocean Engineer's High-Level Perspective"    # Title of book (doesn't appear to show up online, but is in PDF)
author: "Troy W. Heitmann"
copyright: "2024"
logo: "icons/logo.png"    # Path to book logo

description: >-
  This is a description I just added.

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: 2024_Heitmann_Wave_Energy.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/saltynexus/WE_sector_overview  # Online location of your book
#  path_to_book: path/to/your/book  # An optional path to your book relative to root (defaults to repo root)
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Advanced and power-user settings
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser.
    - colon_fence
    - deflist
    - amsmath
    - dollarmath
    - strikethrough
    - linkify
    - tasklist
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "icons/favicon.png" # A path to a favicon image
  use_issues_button: true      # Whether to add an "open an issue" button
  use_repository_button: true  # Whether to add a link to your repository button
  use_edit_page_button: true   # Whether to add an "edit this page" button to pages. If `true`, repository information in "repository" (above): must be filled in
  home_page_in_navbar: true    # Whether to include your home page in the left Navigation Bar

# Buttons to control interactivity
launch_buttons:
  thebe: true
#  notebook_interface: "jupyterlab"
#  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)

